run_test:
	nextflow run workflow.nf -resume --inputsearchresults=data/test.tsv

run_test_nocache:
	nextflow run workflow.nf --inputsearchresults=data/test.tsv

run_test_customstandard:
	nextflow run workflow.nf --inputsearchresults=data/test.tsv --standardfile="CUSTOMFILE" --standardfile_custom=./bin