-include ../Makefile.credentials
include ../Makefile.deploytemplate

WORKFLOW_NAME=rt_model_workflow
TOOL_FOLDER_NAME=rt_model_workflow
WORKFLOW_VERSION=release_31
WORKFLOW_DESCRIPTION="rt_model_workflow"
